begin;

create table if not exists public.user_push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  token text not null,
  platform text not null default 'android',
  enabled boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_push_tokens_platform_check check (platform in ('android', 'ios', 'web')),
  constraint user_push_tokens_token_len check (length(trim(token)) > 20)
);

create unique index if not exists uq_user_push_tokens_token on public.user_push_tokens(token);
create index if not exists idx_user_push_tokens_user_enabled on public.user_push_tokens(user_id, enabled);
create index if not exists idx_user_push_tokens_last_seen on public.user_push_tokens(last_seen_at desc);

drop trigger if exists trg_user_push_tokens_updated_at on public.user_push_tokens;
create trigger trg_user_push_tokens_updated_at
before update on public.user_push_tokens
for each row
execute function public.set_updated_at();

alter table public.user_push_tokens enable row level security;

drop policy if exists user_push_tokens_select_own on public.user_push_tokens;
create policy user_push_tokens_select_own
on public.user_push_tokens
for select
to authenticated
using (user_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists user_push_tokens_insert_own on public.user_push_tokens;
create policy user_push_tokens_insert_own
on public.user_push_tokens
for insert
to authenticated
with check (
  user_id = auth.uid()
  and public.is_validated(auth.uid())
);

drop policy if exists user_push_tokens_update_own on public.user_push_tokens;
create policy user_push_tokens_update_own
on public.user_push_tokens
for update
to authenticated
using (user_id = auth.uid() or public.is_admin(auth.uid()))
with check (user_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists user_push_tokens_delete_own on public.user_push_tokens;
create policy user_push_tokens_delete_own
on public.user_push_tokens
for delete
to authenticated
using (user_id = auth.uid() or public.is_admin(auth.uid()));

grant all on table public.user_push_tokens to service_role;
grant select, insert, update, delete on table public.user_push_tokens to authenticated;
grant usage, select on sequence public.user_push_tokens_id_seq to authenticated;

commit;
